# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Minecraft
minecraft_version=26.2.0
minecraft_version_range=[26.2.0,)

# https://projects.neoforged.net/neoforged/neogradle
neogradle_version=7.1.38

# https://neoforged.net/
neoforge_version=26.2.0.12-beta
neoforge_version_range=[26.2.0.12-beta,)

# Mod Properties
mod_group_id=com.kekie6
mod_id=colorfulazaleas
mod_version=3.4.0+26.2-neoforge
mod_name=Colorful Azaleas
archives_name=ColorfulAzaleas
mod_license=Modified-MIT-License
mod_authors=Kekie6, DaFuqs, OenKrad
mod_description=Adds more colorful Azalea trees to your world!
issue_tracker_url=https://github.com/DaFuqs/ColorfulAzaleas/issues
display_url=https://github.com/DaFuqs/ColorfulAzaleas