# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.1
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version = 3.4.0+26.1
maven_group = com.kekie6
archives_base_name = ColorfulAzaleas

# Dependencies
# check these on https://fabricmc.net/develop
fabric_api_version=0.144.0+26.1