pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'Sponge Snapshots'
            url = 'https://repo.spongepowered.org/repository/maven-public/'
        }
    }
}

rootProject.name = 'ColorfulAzaleas'
// Below is no longer needed since this is not a multi-module project any more - Gradle 9.2.0 is stricter with this
// include("Common", "Fabric") // "Forge"

